
$(document).ready(function(){
    // Function to update employee options based on selected unit
    function updateEmployeeOptions(unit) {
    var employeeSelect = $('#employeeSelect');
    // Clear previous options
    employeeSelect.empty();
    // Add new options based on selected unit
    switch(unit) {
        case 'Boarding':
            employeeSelect.append('<option>Aghna Rizqia Salsabilla</option>');
            employeeSelect.append('<option>Aidah Mubatillah Al Khumsaa</option>');
            employeeSelect.append('<option>Alifuddin Yusuf Adisuseno</option>');
            employeeSelect.append('<option>Ardia Veriana Saputri</option>');
            employeeSelect.append('<option>Ayu Lestari</option>');
            employeeSelect.append('<option>BU MULYANI</option>');
            employeeSelect.append('<option>Fatimah</option>');
            employeeSelect.append('<option>Fitriya Az zahroh,S.Pd</option>');
            employeeSelect.append('<option>Galang Ma&apos;ruf</option>');
            employeeSelect.append('<option>Giant Ramadhan Syah</option>');
            employeeSelect.append('<option>Hasbina Khoiriyah</option>');
            employeeSelect.append('<option>Hidayah Zulirakani, S.Pd.</option>');
            employeeSelect.append('<option>Imam Aji Cahyono</option>');
            employeeSelect.append('<option>Khoirul Arsyad Abdullah</option>');
            employeeSelect.append('<option>Lu&apos;lu&apos; Rosyidah Rofifah</option>');
            employeeSelect.append('<option>Luthfiyah Miftahur Ramdhani</option>');
            employeeSelect.append('<option>M Hanif Aditya</option>');
            employeeSelect.append('<option>Mahmud Al Ghoziri</option>');
            employeeSelect.append('<option>Miftahul Arkhan</option>');
            employeeSelect.append('<option>Muh Ihsan, S.Pd.</option>');
            employeeSelect.append('<option>Muh. Bisri Mustofa</option>');
            employeeSelect.append('<option>Muhammad Syafiq</option>');
            employeeSelect.append('<option>Muhammad Syihabuddin Annur,S.Pd.</option>');
            employeeSelect.append('<option>MUHAMMAD ABDULLAH FAUZAN</option>');
            employeeSelect.append('<option>Mutiara Nurani Suci S.Pd</option>');
            employeeSelect.append('<option>Qonita</option>');
            employeeSelect.append('<option>Rino Saputra</option>');
            employeeSelect.append('<option>Siti Sholikhatun</option>');
            employeeSelect.append('<option>Tursila</option>');
            employeeSelect.append('<option>Zahrotul Khasanah</option>');
            employeeSelect.append('<option>Ziat Rahman Hakim</option>');
            employeeSelect.append('<option>Firda Azaria</option>');
            employeeSelect.append('<option>Luthfia Shifaul Amanah Burhani </option>');
            employeeSelect.append('<option>Aidah </option>');
            employeeSelect.append('<option>Ammar Zain Marzuqi</option>');
            employeeSelect.append('<option>Balqis Sakhaa Ilafi</option>');
            employeeSelect.append('<option>Melinda Retno Diningrum</option>');
            employeeSelect.append('<option>Itsna Rachmawati Dewi</option>');
        break;
        case 'SDICT Surakarta':
            employeeSelect.append('<option>Alfi Mubayyinah, S.Pd</option>');
            employeeSelect.append('<option>Amalia Khusnu, S.Pd</option>');
            employeeSelect.append('<option>Ana Nur Chasanah, Ssi.</option>');
            employeeSelect.append('<option>Ana Sholekah Aszar</option>');
            employeeSelect.append('<option>Apriyani Indri Trisnawati, S.Pd</option>');
            employeeSelect.append('<option>Ari Sugiyono, S. Pd. I., S.Pd.</option>');
            employeeSelect.append('<option>Ayu Oktavia Rosanti, S. Pd.</option>');
            employeeSelect.append('<option>Choirul Anwar, S. Pd</option>');
            employeeSelect.append('<option>Deri Rahmania Luhri, S.Pd</option>');
            employeeSelect.append('<option>Dhian Fitriana, S.Pd.</option>');
            employeeSelect.append('<option>Diana Putri Hidayati</option>');
            employeeSelect.append('<option>Dimas Tegar Mahardhika, S.Pd</option>');
            employeeSelect.append('<option>Dwi Kresna Yulianti, S.Pd</option>');
            employeeSelect.append('<option>Eko Setia Watiningsih, S.S.</option>');
            employeeSelect.append('<option>Elva Herlin Yeliana, S.Pd</option>');
            employeeSelect.append('<option>Endah Aprilia Purwaningrum.M.Pd.</option>');
            employeeSelect.append('<option>Erinda Sari Dwi Astuti, S.Pd</option>');
            employeeSelect.append('<option>Fadiah Azmi Rahmasari, S.Pd.</option>');
            employeeSelect.append('<option>Fadlilah Ramadhani, S.Kom.</option>');
            employeeSelect.append('<option>Hafida Aminindia, S.Pd</option>');
            employeeSelect.append('<option>Heldayani</option>');
            employeeSelect.append('<option>Hendri</option>');
            employeeSelect.append('<option>Kanti Wismanjari, S.Sos., S.Pd.</option>');
            employeeSelect.append('<option>Mochamad Syamsudin Alpalanju, S.Pd</option>');
            employeeSelect.append('<option>Mochammad Jauhari Achmad, S.Pd</option>');
            employeeSelect.append('<option>Mukhsin, S.Pd</option>');
            employeeSelect.append('<option>Nadia Novemi Putri</option>');
            employeeSelect.append('<option>Nanik Yulianti,S.P</option>');
            employeeSelect.append('<option>Purwanto</option>');
            employeeSelect.append('<option>Putri Salwa Salsabila, S.Pd</option>');
            employeeSelect.append('<option>Rahmawati Eki Pujiastuti, S.Pd</option>');
            employeeSelect.append('<option>Regita Asharani, S.T</option>');
            employeeSelect.append('<option>Riski Mukaromah, S.Pd</option>');
            employeeSelect.append('<option>Rosita Pamulia Andani,S.S.</option>');
            employeeSelect.append('<option>Sutarno</option>');
            employeeSelect.append('<option>Taufiq Ma`ruf</option>');
            employeeSelect.append('<option>Tri Wijayanti,S.Pd.M.Pd.</option>');
            employeeSelect.append('<option>Qhoirul Annisa Firdaus, S.Si</option>');
            employeeSelect.append('<option>Megarani Desianingtyas, S.Si</option>');
        break;
        case 'SDII Boyolali':
            employeeSelect.append('<option>Agustin Fatikasari</option>');
            employeeSelect.append('<option>Athifatun Najiyah, S.Pd</option>');
            employeeSelect.append('<option>Bilkhis Sri Maharani, S.Pd</option>');
            employeeSelect.append('<option>Catur Romadloni Pujarwati, S.Pd</option>');
            employeeSelect.append('<option>Fadlan Rifai Al-Irsyad</option>');
            employeeSelect.append('<option>Faradila Ardana, S.Pd</option>');
            employeeSelect.append('<option>Gita Sidiq Kurniawati, S.Pd</option>');
            employeeSelect.append('<option>Hanifa Amri Fatonah</option>');
            employeeSelect.append('<option>Iin Nur Chasanah,S.Pd.</option>');
            employeeSelect.append('<option>Inayah Al Fatihah, S.Pd</option>');
            employeeSelect.append('<option>Intan Jannah Dikhawati, S.Pd</option>');
            employeeSelect.append('<option>Joko Santoso, A.Md</option>');
            employeeSelect.append('<option>Kuntadi, S.Pd</option>');
            employeeSelect.append('<option>Lia Vibrianti, S.Hum</option>');
            employeeSelect.append('<option>Maesaroh, S.E</option>');
            employeeSelect.append('<option>Maryanto</option>');
            employeeSelect.append('<option>Maulidiya, S.Ag</option>');
            employeeSelect.append('<option>Melinda Nur Cahyaningrum, A.Md.Kep</option>');
            employeeSelect.append('<option>Muhammad Amirudin Arrofi&apos;I, S.Pd</option>');
            employeeSelect.append('<option>Muhammad Nurokhim Nawawi, S.Pd</option>');
            employeeSelect.append('<option>Nella Putri Rahmawati, S.Pd</option>');
            employeeSelect.append('<option>Nur Fatimah, S.Pd</option>');
            employeeSelect.append('<option>Nur Halim</option>');
            employeeSelect.append('<option>Rizki Fajar Ramdani,S.H.</option>');
            employeeSelect.append('<option>Rizqi Ashrifah Qurotaayun, S.S</option>');
            employeeSelect.append('<option>Sidik Rohmanto, S.Kom</option>');
            employeeSelect.append('<option>Sunardi</option>');
            employeeSelect.append('<option>Syafi&apos;ul Umam, S.T</option>');
            employeeSelect.append('<option>Syifa Kusuma Wardani</option>');
            employeeSelect.append('<option>Tsabita Faiz Ihsani</option>');
            employeeSelect.append('<option>Umahatul Kibriya, S.Pd</option>');
            employeeSelect.append('<option>Umi Robbayani, S.Pd</option>');
            employeeSelect.append('<option>Wahyu Dwi Fatimah,S.Pd.</option>');
            employeeSelect.append('<option>Yasmina Bilqis Muharromah</option>');
            employeeSelect.append('<option>Yuli Hari Murti, S.Pd.</option>');
            employeeSelect.append('<option>I Gusti Viana Anggita Zunaini, S.Pd</option>');
            employeeSelect.append('<option>Muhammad Furqon Al-Fariqi, S.Pd</option>');
            employeeSelect.append('<option>Dwi Safitri, S.Pd</option>');
        break;
        case 'SDII Karanganyar':
            employeeSelect.append('<option>Ammetyas Kunthi Rachmadhini, S.Pd</option>');
            employeeSelect.append('<option>Arif Munandar, S.Ag.</option>');
            employeeSelect.append('<option>Ismi Wakhidah</option>');
            employeeSelect.append('<option>Medhika Alvania Pebriyani, S.Pd</option>');
            employeeSelect.append('<option>Riyani Halal Hanifah, S.Pd</option>');
            employeeSelect.append('<option>Suparman</option>');
            employeeSelect.append('<option>Tri Wulandari,S.Pd.</option>');
            employeeSelect.append('<option>Yeniar Elka Pramesiana, S.Pd</option>');
        break;
        case 'SDII Klaten':
            employeeSelect.append('<option>Choirul Anwar Al, SPd.</option>');
            employeeSelect.append('<option>Ekawati Yunitasari Putri A.Md.</option>');
            employeeSelect.append('<option>Vela Maria Ulvah,S.Pd.</option>');
            employeeSelect.append('<option>Wiharastro Anan Pudyantoro,S.T, S.Pd.</option>');
            employeeSelect.append('<option>Lulu Fikti Anisah, S.T</option>');
            employeeSelect.append('<option>Fatimah Az Zhara, S.Si</option>');
        break;
        case 'SDII Sragen':
            employeeSelect.append('<option>Anton Munadi, S.Pd.</option>');
            employeeSelect.append('<option>Eka Nydia Ayu,S.Pd.</option>');
            employeeSelect.append('<option>Maimunah, S.Pd.</option>');
            employeeSelect.append('<option>Matsna Sabila Malik, S.H</option>');
            employeeSelect.append('<option>Murniyati, S.Kom</option>');
            employeeSelect.append('<option>Nonik Nataliya,S.P.</option>');
            employeeSelect.append('<option>Nur Aisyah, M.Pd.</option>');
            employeeSelect.append('<option>Rahma Putri Utami, S.P</option>');
            employeeSelect.append('<option>Riana Evi Nurita, S.Pd.</option>');
            employeeSelect.append('<option>Salma Nur Nafisah, S.Pd</option>');
            employeeSelect.append('<option>Sunarto, S.T, S.Pd.</option>');
            employeeSelect.append('<option>Umi Nur Khasanah, M.Pd.I</option>');
            employeeSelect.append('<option>Wahyu Adhi Nugroho,M.Pd.</option>');
            employeeSelect.append('<option>Galih Satria</option>');
            employeeSelect.append('<option>Shedy Amalia Rozzaqi </option>');
            employeeSelect.append('<option>Ellya Saljadziba, S.Pd.</option>');
            employeeSelect.append('<option>Itsla Kamila Nasikh</option>');
        break;
        case 'SDII Sukoharjo':
            employeeSelect.append('<option>Abdullah Akram</option>');
            employeeSelect.append('<option>Abdullah Hasan A</option>');
            employeeSelect.append('<option>Agus Nugroho, S.T., S.Pd</option>');
            employeeSelect.append('<option>Choiriyah,S.Pd.</option>');
            employeeSelect.append('<option>Dinda Rendrasetya Hilmy</option>');
            employeeSelect.append('<option>Fajar Desia Cahyani, S.Pd.I</option>');
            employeeSelect.append('<option>Hilya Faizah Hasanuddin S.Pd</option>');
            employeeSelect.append('<option>Isti Choirunnisa, S.Pd</option>');
            employeeSelect.append('<option>Putra Darmawan, S. S</option>');
            employeeSelect.append('<option>Putri Apriliana</option>');
            employeeSelect.append('<option>Weni Aprilia Pradani, S.Pd</option>');
            employeeSelect.append('<option>Yuli Purwantiningsih</option>');
            employeeSelect.append('<option>Valensa Ihsa Mahendra</option>');
            employeeSelect.append('<option>Islamiah Pratiwi Ayu Larasati, S.Pd</option>');
            employeeSelect.append('<option>Arini Diana Sari</option>');
        break;
        case 'SDII Surakarta':
            employeeSelect.append('<option>Ade Rachmad Said</option>');
            employeeSelect.append('<option>Amin Mustofa,S.Hum.</option>');
            employeeSelect.append('<option>Anggi Firmasari, S.Pd</option>');
            employeeSelect.append('<option>Anita Maharani Kasnara, SS</option>');
            employeeSelect.append('<option>Annisa Lina Syarifah,S.Pd</option>');
            employeeSelect.append('<option>Arif Mashudi, ST</option>');
            employeeSelect.append('<option>Arwan Joko Supriyono, S.Pd.I</option>');
            employeeSelect.append('<option>Aulia Firdausia Putri,S,Pd</option>');
            employeeSelect.append('<option>Azimatul Afifah,S.H.</option>');
            employeeSelect.append('<option>Chamimah Ahsaniyati,A.Mk</option>');
            employeeSelect.append('<option>Dessya Diah Rahmawati, S.Pd</option>');
            employeeSelect.append('<option>Dika Ananda, S.Pd</option>');
            employeeSelect.append('<option>Efa Wahyuni, S.I.Kom</option>');
            employeeSelect.append('<option>Eri Munandar</option>');
            employeeSelect.append('<option>Fadlilah Din Rohimin, S.Pd</option>');
            employeeSelect.append('<option>Fatima Azzahra, S.Pd.I.</option>');
            employeeSelect.append('<option>Fatimah Azizah,S.KM.</option>');
            employeeSelect.append('<option>Fawwaz Dhiyaaul Haq, S.Pd.</option>');
            employeeSelect.append('<option>Fitria Yulianti S.Sos.</option>');
            employeeSelect.append('<option>Hazna Wahyuningsih,S.Pd.</option>');
            employeeSelect.append('<option>Imaniar Dyah Rahmawati, S.Pd</option>');
            employeeSelect.append('<option>Kudratullah, S.S.</option>');
            employeeSelect.append('<option>Lia Adhedia, SS</option>');
            employeeSelect.append('<option>Lisna Rahmawati</option>');
            employeeSelect.append('<option>Listyowati,S.Pd</option>');
            employeeSelect.append('<option>Lukman Nul Hakim, S.Pd.</option>');
            employeeSelect.append('<option>Lutfi Istiqomah, S.T, S.Pd</option>');
            employeeSelect.append('<option>M. Adi Ramelan</option>');
            employeeSelect.append('<option>Mais Al Mubarok Fi Daroini,S.Pd.</option>');
            employeeSelect.append('<option>Malik Argo Santoso, S.Pd, M.Or</option>');
            employeeSelect.append('<option>Mashuri, S. PdI</option>');
            employeeSelect.append('<option>Mohammad Thoriq,S.Pd.</option>');
            employeeSelect.append('<option>Muflichatun Nisa`,S.S.</option>');
            employeeSelect.append('<option>Muhammad Mustaghfir Al-Anshori, S.Pd</option>');
            employeeSelect.append('<option>Ninik Suparyanti, S.Sos</option>');
            employeeSelect.append('<option>Nur Azizah, S.S</option>');
            employeeSelect.append('<option>Nur Rohmah Hidayanti</option>');
            employeeSelect.append('<option>Nurfita Widyastuti,S.Pd.</option>');
            employeeSelect.append('<option>Nurul Fadhilah, S.Pd</option>');
            employeeSelect.append('<option>Pinky Tri Anggilia,A.Md</option>');
            employeeSelect.append('<option>Putri Eko Novita Sary,S.Pd</option>');
            employeeSelect.append('<option>Ria Intan Prasetyo,S.Pd</option>');
            employeeSelect.append('<option>Sholimin</option>');
            employeeSelect.append('<option>Siti Romelah, S.Pd</option>');
            employeeSelect.append('<option>Sri Wachyuningsih,S.Pd.,Gr.</option>');
            employeeSelect.append('<option>Suparno,S.T</option>');
            employeeSelect.append('<option>Tim Komputer</option>');
            employeeSelect.append('<option>Titis Dyah Ekowati, S.Pd</option>');
            employeeSelect.append('<option>Tukiyo </option>');
            employeeSelect.append('<option>Uswahtun Hassanah,S.Pd.</option>');
            employeeSelect.append('<option>Uswatun Khasanah, S.Pd</option>');
            employeeSelect.append('<option>Wahyu Sari Mukti, S.Pd</option>');
            employeeSelect.append('<option>Yosi Anggraeni Wisnu Kusumaningtyas, S.Pd</option>');
            employeeSelect.append('<option>Yuni Siswanti, S.Pd</option>');
            employeeSelect.append('<option>Zaini Muharom, S. S., S.Pd.</option>');
            employeeSelect.append('<option>Zeni Vera Wati, S.Pd</option>');
            employeeSelect.append('<option>Mufti Khoirunnisa&apos;, S.Pd</option>');
        break;
        case 'SDII Yogyakarta':
            employeeSelect.append('<option>Ajeng Aprilia Husaeni, S.Pd</option>');
            employeeSelect.append('<option>Kartika Desy Purwanti,S.Pd.</option>');
            employeeSelect.append('<option>Muhammad Naufal Ilyas Saputra</option>');
        break;
        case 'SDTQ Surakarta':
            employeeSelect.append('<option>Abbad Said Muhammad,S.Pd</option>');
            employeeSelect.append('<option>Abu Dawud Kasruri</option>');
            employeeSelect.append('<option>Agung Wahyu Utomo, S.Pd</option>');
            employeeSelect.append('<option>Anis Setyowati, S.Pd</option>');
            employeeSelect.append('<option>Annur Indah Sari, S.Pd.I</option>');
            employeeSelect.append('<option>Arif Budiyono.S.Pd.I.</option>');
            employeeSelect.append('<option>Arista Kunti Habsari, S.Pd</option>');
            employeeSelect.append('<option>Artanti Wulansuci Utami, S.Pd</option>');
            employeeSelect.append('<option>Ayu Sholichah, S.S</option>');
            employeeSelect.append('<option>Azizah Al-Ayyubi</option>');
            employeeSelect.append('<option>Devie Ayu Arinikha,S.PdI</option>');
            employeeSelect.append('<option>Dewi Mifta Maya Andira, S.Pd</option>');
            employeeSelect.append('<option>Dizki Aji Pangestu, S.Pd</option>');
            employeeSelect.append('<option>Dyah Astari, S.T.</option>');
            employeeSelect.append('<option>Elya Retna Purwaningtyas, S.T</option>');
            employeeSelect.append('<option>Ernawati, S.Sos.</option>');
            employeeSelect.append('<option>Fathullah, SE. Sy</option>');
            employeeSelect.append('<option>Fatnia Ulul Arfiyanti,S.Pd.</option>');
            employeeSelect.append('<option>Hastinnailul Mawadah, S.Kep</option>');
            employeeSelect.append('<option>Indah Kurniawati, S.S., S.Pd</option>');
            employeeSelect.append('<option>Indriyani, S.Pd</option>');
            employeeSelect.append('<option>Khoirun Nisa,S.PdI</option>');
            employeeSelect.append('<option>Kuswardani Dyah Ayu Kusumaningrum, S.Ag</option>');
            employeeSelect.append('<option>Luth Hafizh Bahtiar, S.Pd</option>');
            employeeSelect.append('<option>Lutviyana Galih Paswatiningsih,S.H.</option>');
            employeeSelect.append('<option>Masrukan,S,Pd.</option>');
            employeeSelect.append('<option>Melani Ismoyowati, S.Pd</option>');
            employeeSelect.append('<option>Muhammad amin</option>');
            employeeSelect.append('<option>Muhammad Faisal Alaq Qodrian Efenfdi</option>');
            employeeSelect.append('<option>Muhammad Mushab</option>');
            employeeSelect.append('<option>Munawaroh,S.Pd.I</option>');
            employeeSelect.append('<option>Nafi Umi Atmaja, S.Pd</option>');
            employeeSelect.append('<option>Nanik Sulistiyo Rahayu</option>');
            employeeSelect.append('<option>Nur Anisa</option>');
            employeeSelect.append('<option>Nurul Humaeroh Kartiko Winar, S.Pd</option>');
            employeeSelect.append('<option>Nur`aini, SPd.</option>');
            employeeSelect.append('<option>Paramadina Santri</option>');
            employeeSelect.append('<option>Rin Fibriana, S.Psi.,S.Pd.I</option>');
            employeeSelect.append('<option>Rizal Mustofa</option>');
            employeeSelect.append('<option>Rohmat Roi Waldi, S.Pd</option>');
            employeeSelect.append('<option>Siti Chotijah, S.Pd.</option>');
            employeeSelect.append('<option>Siti Nurhayati, S.Pi</option>');
            employeeSelect.append('<option>Siti Rofiyatun,S.Pd</option>');
            employeeSelect.append('<option>Sri Utami, S.Pd.I.</option>');
            employeeSelect.append('<option>Sumiyati,S.Hum.</option>');
            employeeSelect.append('<option>Wahyu Catur Rini</option>');
            employeeSelect.append('<option>Warti, S. Si.</option>');
            employeeSelect.append('<option>Zhahrul Makhfud, S.Pd</option>');
            employeeSelect.append('<option>Dina Arifatul Khusna</option>');
            employeeSelect.append('<option>Maia Ameilyana Zapin </option>');
            employeeSelect.append('<option>Ummu Izzatul Uswatun khalisah </option>');
            employeeSelect.append('<option>Ari Rahmawati </option>');
            employeeSelect.append('<option>Ahmad Fahmi Alfian</option>');
            employeeSelect.append('<option>Dekat Selfiana</option>');
        break;
        case 'SMA ABBS':
            employeeSelect.append('<option>Abd Azis, S.Pd.I.</option>');
            employeeSelect.append('<option>Abdulloh Al Haris Dzulfikri,S.Pd</option>');
            employeeSelect.append('<option>Achrudin, S.Pd., Gr.</option>');
            employeeSelect.append('<option>Adilah Hasna,S.Pd.</option>');
            employeeSelect.append('<option>Agung Sularso, S.Pd,Gr.</option>');
            employeeSelect.append('<option>Ahmad Subandi</option>');
            employeeSelect.append('<option>Alfi Suryani Yusuf,S.Pd</option>');
            employeeSelect.append('<option>Amira Muflicha Daraini, M.Pd.</option>');
            employeeSelect.append('<option>Amirul Setiawan,S.Pd.</option>');
            employeeSelect.append('<option>Anggi Puspa Wijayanti Wiaz, S.Sos</option>');
            employeeSelect.append('<option>Anna Rafaidah, S.Pd.</option>');
            employeeSelect.append('<option>Aripiyanto</option>');
            employeeSelect.append('<option>Asnia Novitasari. AM, M.E</option>');
            employeeSelect.append('<option>Asy Syifa Labibah,S.Pd., M.Sc</option>');
            employeeSelect.append('<option>Aulia Nur Ridwan, S.Pd., Gr.</option>');
            employeeSelect.append('<option>Azhar Umam, S.Pd</option>');
            employeeSelect.append('<option>Dhiyas Fatin Nuha,S.Pd.</option>');
            employeeSelect.append('<option>Dwi Noviasih Pratama,S.Pd</option>');
            employeeSelect.append('<option>Fadhilah Kusumasari, S.Pd</option>');
            employeeSelect.append('<option>Fandi Agus Irawan, S.Pd</option>');
            employeeSelect.append('<option>Farida Leni Kusumawati, S.Pd</option>');
            employeeSelect.append('<option>Fatimah Azzahroh, S.Pd</option>');
            employeeSelect.append('<option>Fatimah Zahro Assidiqoh, S.Pd</option>');
            employeeSelect.append('<option>Febrianto Agus Wirasto,A.Md.</option>');
            employeeSelect.append('<option>Fitri Nur Hardiyani, S.Pd.I</option>');
            employeeSelect.append('<option>Frenika Widyasari, M.Pd</option>');
            employeeSelect.append('<option>Hana Agustyaningrum, M.Pd.</option>');
            employeeSelect.append('<option>Hasna Alfasina,S.Pd</option>');
            employeeSelect.append('<option>Hesti Indah Mifta Nur&apos;aini, S.Pd, M.Pd</option>');
            employeeSelect.append('<option>Ina Yuliyati,S.Pd.</option>');
            employeeSelect.append('<option>Inna Rizki Apriyanti, M.Pd., Gr.</option>');
            employeeSelect.append('<option>Intan Widya Pangestika, S.Pd, M.Si</option>');
            employeeSelect.append('<option>Isnaini Umi Nurhasanah,M.Pd</option>');
            employeeSelect.append('<option>Isykarima Amalia Vita Noor Izzaty, S.Pd</option>');
            employeeSelect.append('<option>M. Thoriq Hanafi, S.Pd</option>');
            employeeSelect.append('<option>Marwanto</option>');
            employeeSelect.append('<option>Mochamad Hafid Rozaqi</option>');
            employeeSelect.append('<option>Muhammad Abdul Azis, S.Pd.</option>');
            employeeSelect.append('<option>Muhammad Zaenuddin, S.E.I</option>');
            employeeSelect.append('<option>Naimina Restu An Nabil, S.Pd.</option>');
            employeeSelect.append('<option>Nasyalina Dwinta, S.Pd</option>');
            employeeSelect.append('<option>Nina Setyowati, S.Pd</option>');
            employeeSelect.append('<option>Novilia Nugraheni, M.Pd</option>');
            employeeSelect.append('<option>Nur Masitoh,S.Pd.</option>');
            employeeSelect.append('<option>Nur Shofa Riyana, S.Si</option>');
            employeeSelect.append('<option>Nurul Fadhila Firdaus, S.Pd</option>');
            employeeSelect.append('<option>Ocnatias Eka Saputri, S.Kep, M.Psi</option>');
            employeeSelect.append('<option>Putera Islamiyadi Rahmatullah,S.Kom.</option>');
            employeeSelect.append('<option>Putri Oktaviani, S.Pd</option>');
            employeeSelect.append('<option>Qothrun Nada Husna</option>');
            employeeSelect.append('<option>Rahma Nur Afifah, S.Pd</option>');
            employeeSelect.append('<option>Rajini,S.Pd,M.Pd</option>');
            employeeSelect.append('<option>Ratih Tri Wijayanti, S.Pd</option>');
            employeeSelect.append('<option>RENGGA NGESTHI PAMBUKA, S.PD</option>');
            employeeSelect.append('<option>Rini Kurniasih, M.Pd</option>');
            employeeSelect.append('<option>Salmaa Khoirun Nisaa&apos;, S.Kom</option>');
            employeeSelect.append('<option>Sari Melati Kusuma Astuti, S.Pd.</option>');
            employeeSelect.append('<option>Sela Mawarti, M.Pd.</option>');
            employeeSelect.append('<option>Shofwa Annisaa, S.Pd.</option>');
            employeeSelect.append('<option>Siska Wahyuningtyas Retno Wulandari, S.Pd.</option>');
            employeeSelect.append('<option>Solikatun, S.Pd</option>');
            employeeSelect.append('<option>Sri Mulyani, S.Pd</option>');
            employeeSelect.append('<option>Supriyono</option>');
            employeeSelect.append('<option>Sutarto</option>');
            employeeSelect.append('<option>Syih Almayanti</option>');
            employeeSelect.append('<option>Teguh Umarudin,S.Pd</option>');
            employeeSelect.append('<option>Titik Purwanti,S.Si.</option>');
            employeeSelect.append('<option>Tyas Wisnuwardani, S.Pd</option>');
            employeeSelect.append('<option>Umi Wahidatul Latifah, S.Pd.</option>');
            employeeSelect.append('<option>Uswatun Hasanah,S.Pd</option>');
            employeeSelect.append('<option>Virliana Annida Rekkayushar, S.Kom</option>');
            employeeSelect.append('<option>Wiji Setyo Utami, S.Pd</option>');
            employeeSelect.append('<option>Yunita Sari, A.Md</option>');
            employeeSelect.append('<option>Zahrotun Hanifah, M.Pd</option>');
            employeeSelect.append('<option>Zuly Irawan, S.Kom.</option>');
            employeeSelect.append('<option>Jonanda Fattah Anugerah, S.Pd. </option>');
            employeeSelect.append('<option>Rikha Putri Devianti</option>');
        break;
        case 'SMP ABBS':
            employeeSelect.append('<option>Alla&apos; Junia Nurdin, S.Pd</option>');
            employeeSelect.append('<option>Andi Wijayanto</option>');
            employeeSelect.append('<option>Eka Noer Maya Sari, S.T</option>');
            employeeSelect.append('<option>Fatma Roudhotul Rafida Kolis, S.Pd., Gr.</option>');
            employeeSelect.append('<option>Hari Rohmah, S.Pd</option>');
            employeeSelect.append('<option>Ida Aryani, S.  Sos.</option>');
            employeeSelect.append('<option>Iin Indah Saputri,S.Pd.</option>');
            employeeSelect.append('<option>Joko Ariyanto,S.T.</option>');
            employeeSelect.append('<option>Lutfa Usaidah</option>');
            employeeSelect.append('<option>Muamar Fariq Salafy, S.Pd, Gr.</option>');
            employeeSelect.append('<option>Muhammad Fahmi Aziz, S.Psi</option>');
            employeeSelect.append('<option>Rifqi Syarifudin</option>');
            employeeSelect.append('<option>Sharih Shadri,S.S.</option>');
            employeeSelect.append('<option>Sinta Fitriana, S. Pd</option>');
            employeeSelect.append('<option>Siti Asiyah Wardatul Jannah, S.Pd</option>');
            employeeSelect.append('<option>Siti Khoimah, S. Pd.</option>');
            employeeSelect.append('<option>Arvino Nurvieri Kusuma</option>');
            employeeSelect.append('<option>Scundy Nourma Pratiwi, M.Pd.</option>');
        break;
        case 'SMPII Boyolali':
            employeeSelect.append('<option>Ami Nitami, S.Pd</option>');
            employeeSelect.append('<option>Dwi Indah Royani,S.Pd.</option>');
            employeeSelect.append('<option>Essy Dian Pratiwi, M.Pd</option>');
            employeeSelect.append('<option>Farrasa Uswatun Hasanah, B.A</option>');
            employeeSelect.append('<option>Fathimah Al-Zuhri,S.Pd</option>');
            employeeSelect.append('<option>Habib Hasan</option>');
            employeeSelect.append('<option>Lydia Carolin, BA</option>');
            employeeSelect.append('<option>Mohamad Arif Maulana,S.Pd.</option>');
            employeeSelect.append('<option>Muhammad Rois Adzkia, S.I.P</option>');
            employeeSelect.append('<option>Naili Mawadda, S.Si</option>');
            employeeSelect.append('<option>Phaksi Arwendha, M.Sn</option>');
            employeeSelect.append('<option>Purnamawati, S.Pd</option>');
            employeeSelect.append('<option>Rina Irawati, S.Pd</option>');
            employeeSelect.append('<option>Ulfiatu Nur Azizah</option>');
            employeeSelect.append('<option>Zeni Prasetyo</option>');
            employeeSelect.append('<option>Mutiara Nurani Suci</option>');
            employeeSelect.append('<option>Tungga Pramudya Utama</option>');
            employeeSelect.append('<option>Tia Izzah Fathiya</option>');
            employeeSelect.append('<option>Dani Dwi Susanti </option>');
        break;
        case 'SMPII Karanganyar':
            employeeSelect.append('<option>Arif Hidayat, S. Pd</option>');
            employeeSelect.append('<option>Darsono, S.Pd.</option>');
            employeeSelect.append('<option>Fhitri Indah Sari, S.Pd</option>');
            employeeSelect.append('<option>Indra Tri Ariyadi Suseno,S.Pd.</option>');
            employeeSelect.append('<option>Khusnul Karimah, S.Pd</option>');
            employeeSelect.append('<option>Mulyadi</option>');
            employeeSelect.append('<option>Nursita Yuliana</option>');
            employeeSelect.append('<option>Nurul Rizqa</option>');
            employeeSelect.append('<option>Nurul Rizqa b</option>');
            employeeSelect.append('<option>Retno Kusuma Astuti, S.Pd</option>');
        break;
        case 'SMPII Klaten':
            employeeSelect.append('<option>Ana Susanti, S. Pd</option>');
            employeeSelect.append('<option>Retno Wiyanti, S.Pd</option>');
            employeeSelect.append('<option>Muhammad Fachrudin Alwi, S.S</option>');
        break;
        case 'SMPII Sukoharjo':
            employeeSelect.append('<option>alqaan maqbullah ilmi, S.Pd., M.Pd., M.Si.</option>');
            employeeSelect.append('<option>Amatullah Ashshobriatu Nuha, S.Pd</option>');
            employeeSelect.append('<option>Anas Tas Nia Dewi Nur Komaria, S.Pd</option>');
            employeeSelect.append('<option>Anggita Widya Nugroho, S.Pd.</option>');
            employeeSelect.append('<option>Annisa Dwi Nursanti, S.Pd</option>');
            employeeSelect.append('<option>Ibrohim Abdul Alfatahu</option>');
            employeeSelect.append('<option>Mochammad Rizkia Putra</option>');
            employeeSelect.append('<option>Mukhlis Kurnia Aji, S.T</option>');
            employeeSelect.append('<option>Nur Afifah, S.Kom</option>');
            employeeSelect.append('<option>Putri Nurika Anggraini, M.Pd</option>');
            employeeSelect.append('<option>Shalindri Saraswati, S.Pd</option>');
            employeeSelect.append('<option>Yuzka Faiz Ad dzakie</option>');
            employeeSelect.append('<option>Luthfiyah Miftahur Ramdhani </option>');
        break;
        case 'SMPII Surakarta':
            employeeSelect.append('<option>Adi Cahyo Nugroho</option>');
            employeeSelect.append('<option>Adi Irma Suryadi, S.Pd, M.Pd</option>');
            employeeSelect.append('<option>Adila Rahmah, S.Pd, M.Pd.</option>');
            employeeSelect.append('<option>Ahmad Bayu Abdulloh</option>');
            employeeSelect.append('<option>Ahmad Fauzi</option>');
            employeeSelect.append('<option>AHMAD SYAIFUL</option>');
            employeeSelect.append('<option>Aji Kusuma Negara</option>');
            employeeSelect.append('<option>Alfia Setya Rahmadevi, S.Pd</option>');
            employeeSelect.append('<option>Arlina Yuliastanti,S.Pd.</option>');
            employeeSelect.append('<option>Auriga Maulana Khasan, M.Pd</option>');
            employeeSelect.append('<option>Banna Handiyanto,S.Pd.I</option>');
            employeeSelect.append('<option>Danang Dwi Pambudi S. Pd</option>');
            employeeSelect.append('<option>Dewi Nur&apos;aini</option>');
            employeeSelect.append('<option>Dewi Wijayanti,S.Kom</option>');
            employeeSelect.append('<option>Ekawati,S.Pd.</option>');
            employeeSelect.append('<option>Farras Astri Firyadani, S.Pd</option>');
            employeeSelect.append('<option>Fitri Nur Kholifah,S.Pd</option>');
            employeeSelect.append('<option>Fitria Rachmawati Zain,S.Pd.</option>');
            employeeSelect.append('<option>Hafiz Kurniawan, S.Pd</option>');
            employeeSelect.append('<option>Hannah Ummu Atikah, S.Ag</option>');
            employeeSelect.append('<option>Hari Prasetyo, A.Md.</option>');
            employeeSelect.append('<option>Heni Susilowati, S. Pd</option>');
            employeeSelect.append('<option>Idhan Khalik</option>');
            employeeSelect.append('<option>Ikhwan Caesar Amri Pradana, S.Pd</option>');
            employeeSelect.append('<option>Isti Qomah Nurul Izzati, S.Pd</option>');
            employeeSelect.append('<option>Joan Nofila Nurlinita,S.Pd.</option>');
            employeeSelect.append('<option>Khairun, S.Ag</option>');
            employeeSelect.append('<option>Kristantono,S.Pd.I</option>');
            employeeSelect.append('<option>Kurniawan Ridho Saputro,S.Pd</option>');
            employeeSelect.append('<option>Laili Khairun Nisa&apos;, S.Pd</option>');
            employeeSelect.append('<option>Lia Nuryani</option>');
            employeeSelect.append('<option>Luqfi Nurul Setiawan, S.Pd</option>');
            employeeSelect.append('<option>Mia Febriana,M.Pd.</option>');
            employeeSelect.append('<option>Mohamad Darril Hermawan, S.Pd.</option>');
            employeeSelect.append('<option>Muhammad Sultan Izzudin</option>');
            employeeSelect.append('<option>MUSFIQ AMRULLOH, S.Pd.</option>');
            employeeSelect.append('<option>Nafakah Aria Perkasa, S.Pd, M.Pd</option>');
            employeeSelect.append('<option>Nisa Ul Haq</option>');
            employeeSelect.append('<option>Nor Azizah, S.Sos</option>');
            employeeSelect.append('<option>Nurul Hidayah Kobir, S.Pd</option>');
            employeeSelect.append('<option>Nurul Hidayati,S.Pd</option>');
            employeeSelect.append('<option>Rina Wijayanti, S. Pd</option>');
            employeeSelect.append('<option>Rizal Mahfudin, S.Pd.</option>');
            employeeSelect.append('<option>Rizky Andriyanto, S.Pd</option>');
            employeeSelect.append('<option>Rois Patoni</option>');
            employeeSelect.append('<option>Saraswati,S.Si.</option>');
            employeeSelect.append('<option>Siti Zamronah Rizqiah</option>');
            employeeSelect.append('<option>Sri Wahyuni,S.Pd.</option>');
            employeeSelect.append('<option>Sriyanto,S.E</option>');
            employeeSelect.append('<option>Sutarto</option>');
            employeeSelect.append('<option>Titik Maryatun</option>');
            employeeSelect.append('<option>Trully Sanuri Damayanti, S.Si</option>');
            employeeSelect.append('<option>Ulfa Nurul Kurniawati</option>');
            employeeSelect.append('<option>Wela Ardha Permatasari, S.Pd</option>');
            employeeSelect.append('<option>Widhi Haryanto</option>');
            employeeSelect.append('<option>Yoki Wirawan, S.Pd</option>');
            employeeSelect.append('<option>Yudi Prasetiyo, S.Kom.</option>');
            employeeSelect.append('<option>Yustien Pramita Hapsari, S.Pd</option>');
            employeeSelect.append('<option>Zaenal Baharudin, A.Md</option>');
            employeeSelect.append('<option>Muh Bisri Mustofa </option>');
        break;
        case 'SMPII Yogyakarta':
            employeeSelect.append('<option>Mefta Rizki Qurrat &apos;Aini, S.Pd</option>');
            employeeSelect.append('<option>Muhammad Nadir</option>');
            employeeSelect.append('<option>Malisa Alifatul Izza Hapsari</option>');
            employeeSelect.append('<option>Nurul Khafidoh, S.S.</option>');
        break;
        case 'SSU':
            employeeSelect.append('<option>Aji Wibowo</option>');
            employeeSelect.append('<option>Dwi Haryanto</option>');
            employeeSelect.append('<option>Yanuar Hafidh F</option>');
        break;
        case 'TKII Boyolali':
            employeeSelect.append('<option>Aida Dewi Astuti,S.Sos.</option>');
            employeeSelect.append('<option>Anisa Wafa Aulia,S.Pd.</option>');
            employeeSelect.append('<option>Annisa Amalia Rahmah, S.Pd</option>');
            employeeSelect.append('<option>Apri Ismulandari, S.Pd</option>');
            employeeSelect.append('<option>Arviana Dwi Suhartanti, S.kom</option>');
            employeeSelect.append('<option>Azizatul Itsna,S.Pd.</option>');
            employeeSelect.append('<option>Beltin Seftiana, S.Pd</option>');
            employeeSelect.append('<option>Dewi Rahmani</option>');
            employeeSelect.append('<option>Dinah Lestari, A.Md</option>');
            employeeSelect.append('<option>Fajar Hari Tamara, S.Pd</option>');
            employeeSelect.append('<option>Farida Nur Handayani, S.Pd.</option>');
            employeeSelect.append('<option>Hasna Atika Ningtyas</option>');
            employeeSelect.append('<option>Inannisa Izzatul Ni&apos;mah,S.Pd.</option>');
            employeeSelect.append('<option>Intan Kumala Sari, S.Pd</option>');
            employeeSelect.append('<option>Kusnia Setiarti,S.Pd</option>');
            employeeSelect.append('<option>Nia Astutik, S.Pd</option>');
            employeeSelect.append('<option>Niken Popy Nur Laili Febriana, S.Pd.,Gr</option>');
            employeeSelect.append('<option>Nisaulmahmudah Nandipinta, S.Psi</option>');
            employeeSelect.append('<option>Nur Haqiqi, S.Pd</option>');
            employeeSelect.append('<option>Nurul Istiqomah, S.Pd</option>');
            employeeSelect.append('<option>Rufaida Umi Sholikhah,S.Pd.</option>');
            employeeSelect.append('<option>Rustia Wahyu Wijayanti, S.Pd</option>');
            employeeSelect.append('<option>Wahyu Arinta Rizki, S.Si</option>');
            employeeSelect.append('<option>Win Yunidar Setyawati, S.Pd</option>');
            employeeSelect.append('<option>Winda Wahyu Dianty, S.Pd, M.Pd</option>');
            employeeSelect.append('<option>Yuliana Sari, S.Pd</option>');
            employeeSelect.append('<option>Risma Khoirun Nisak, S. Pd</option>');
        break;
        case 'TKII Karanganyar':
            employeeSelect.append('<option>Amany Hidayah, S.Pd</option>');
            employeeSelect.append('<option>Fadhilah Nur Hidayah,S.S.</option>');
            employeeSelect.append('<option>Mikami Esta Anggraeni, S.Ak</option>');
            employeeSelect.append('<option>Pepsi Febriyanti, S.Pd</option>');
            employeeSelect.append('<option>Praditya Ayu Cahyani, S.Pd</option>');
            employeeSelect.append('<option>Rina Budhi Hidayah, S.Pd</option>');
            employeeSelect.append('<option>Tri Handayani, S.Pd</option>');
            employeeSelect.append('<option>Widya Ratnaningsih</option>');
            employeeSelect.append('<option>Wiwit Nur Aini, S.Pd</option>');
            employeeSelect.append('<option>Amaliya nur Azizah,S.Pd</option>');
        break;
        case 'TKII Klaten':
            employeeSelect.append('<option>Dewi Fathona Rahmawati</option>');
            employeeSelect.append('<option>Muhammad Alfitra, S.Pd</option>');
            employeeSelect.append('<option>Umi Sholichah, S.Pd</option>');
            employeeSelect.append('<option>Anisa Oktafia Fitriani, S.Pd.</option>');
        break;
        case 'TKII Sukoharjo':
            employeeSelect.append('<option>Ahma Nur Aisyah, S.Pd</option>');
            employeeSelect.append('<option>Amalia Nisa Sholehah</option>');
            employeeSelect.append('<option>Andira Koza Laksita, S.Psi</option>');
            employeeSelect.append('<option>Annisa Fathaniah Anwar, S.Psi, S.Pd</option>');
            employeeSelect.append('<option>Aulia Umi Valentina, S.S</option>');
            employeeSelect.append('<option>Dinda Nadilla Sandy, S.Pd</option>');
            employeeSelect.append('<option>Fatimah Zakiyah, S.Kep.</option>');
            employeeSelect.append('<option>Ika Devi Pancasilawati, S.Pd</option>');
            employeeSelect.append('<option>Nilna Dati Layyina, S.S</option>');
            employeeSelect.append('<option>Nur Rohmawati, S.Pd</option>');
            employeeSelect.append('<option>Rosmalita Putri Isnaini, S.Pd</option>');
            employeeSelect.append('<option>Rusdi Ana Luthfi, S. S. I</option>');
            employeeSelect.append('<option>Siti Fatimah, S.H.</option>');
        break;
        case 'TKII Surakarta':
            employeeSelect.append('<option>Alfinna Setya Rahayu</option>');
            employeeSelect.append('<option>Anisa Rosilawati Qurotul A&apos;yun, S.Pd</option>');
            employeeSelect.append('<option>Desi Nurjayanti,S.Pd.</option>');
            employeeSelect.append('<option>Dessy Nuraini A., SS</option>');
            employeeSelect.append('<option>Dian Rifiah Irawati</option>');
            employeeSelect.append('<option>Dwi Erika Mufdiyati, SS</option>');
            employeeSelect.append('<option>Ervi Ari Listyani Wahono,S.Pd.</option>');
            employeeSelect.append('<option>Friska Arsalina, S.P.</option>');
            employeeSelect.append('<option>Imawati Rodhiyyana, S.Pd</option>');
            employeeSelect.append('<option>Ita Rusdiana, S. Pd</option>');
            employeeSelect.append('<option>Khoiri Hidayati</option>');
            employeeSelect.append('<option>Laela Nur &apos;Aini, S.Pd</option>');
            employeeSelect.append('<option>Laily Istifaiyah, S.Pd</option>');
            employeeSelect.append('<option>Malinda Hidayanti, S.Pd</option>');
            employeeSelect.append('<option>Marito Juli Yanti, S.Ag</option>');
            employeeSelect.append('<option>Mugi Rahayu,S.Pd.</option>');
            employeeSelect.append('<option>Nathasya Cindy Claudya</option>');
            employeeSelect.append('<option>Nina Nuroniah, S. Pd</option>');
            employeeSelect.append('<option>Nisa Hidayati</option>');
            employeeSelect.append('<option>Qonitatul Mahmudah, S.S</option>');
            employeeSelect.append('<option>Reny Apriyani, SE</option>');
            employeeSelect.append('<option>Siti Nur Khasanah,A.Mkg</option>');
            employeeSelect.append('<option>Siti Rochimah,S.Pd.</option>');
            employeeSelect.append('<option>Uswatun Hasanah, S.S</option>');
            employeeSelect.append('<option>Vylla Nurika Sari,S.Pd.</option>');
            employeeSelect.append('<option>Yuni Irawati, S.E.</option>');
            employeeSelect.append('<option>Yunita Miftakhunisa, S.Pd</option>');
            employeeSelect.append('<option>Sabiqoh Dwi Wahyuni</option>');
            employeeSelect.append('<option>Fauziah shoimah S.Pd</option>');
            employeeSelect.append('<option>Imawati</option>');
        break;
        case 'TKII Yogyakarta':
            employeeSelect.append('<option>Alyarahma Nur Aisya, S. T. P.</option>');
            employeeSelect.append('<option>Fidiana Nurhantari,S.Psi.</option>');
            employeeSelect.append('<option>Amrina Rosyada </option>');
        break;
        case 'TKQP Surakarta':
            employeeSelect.append('<option>Ardistha Yuliana Purbasari, S.Pd</option>');
            employeeSelect.append('<option>Dewi Ambarsari</option>');
            employeeSelect.append('<option>Dwi Toto Sarjono</option>');
            employeeSelect.append('<option>Farida Nur Aini,S.E.</option>');
            employeeSelect.append('<option>Ina Indrawati,S.Pd.</option>');
            employeeSelect.append('<option>Ira Desy Kusliniawati, S.Pd</option>');
            employeeSelect.append('<option>Latifatun Nisa,S.Pd.</option>');
            employeeSelect.append('<option>Nur Endah</option>');
            employeeSelect.append('<option>Putri Cahya Sari, S.Sn</option>');
            employeeSelect.append('<option>Ratih Listeriyadi, S.Si</option>');
            employeeSelect.append('<option>Rizky Faujiah, S.Kom</option>');
            employeeSelect.append('<option>Stefi Aulia Putri, S.Pd</option>');
            employeeSelect.append('<option>Tuwiyem, S. Pd</option>');
            employeeSelect.append('<option>Lina Dani Lestari, S.Pd</option>');
        break;
        case 'Yayasan':
            employeeSelect.append('<option>Ahmad Sulaeman, M.Pd</option>');
            employeeSelect.append('<option>Dian Octavianah,S.P.</option>');
            employeeSelect.append('<option>dr. Syayma Karimah</option>');
            employeeSelect.append('<option>Fahrizal Miftahuddin</option>');
            employeeSelect.append('<option>Farida Nur  `Aini, S. Sos</option>');
            employeeSelect.append('<option>Fityatul Muharromah, S.P.</option>');
            employeeSelect.append('<option>Imam Samodra, S.Si., M.Si. Gr.</option>');
            employeeSelect.append('<option>Khanifudin, M.Pd.</option>');
            employeeSelect.append('<option>Khoiruddin, M.Sc.</option>');
            employeeSelect.append('<option>Muhammad Ridwanullah</option>');
            employeeSelect.append('<option>Muhammad Rizki Almalik</option>');
            employeeSelect.append('<option>Mulyani</option>');
            employeeSelect.append('<option>Nadya Nuryaningtyas</option>');
            employeeSelect.append('<option>Nur Islami Prayoganing Ayu, S.I.Kom</option>');
            employeeSelect.append('<option>Nurul Waridatil Zulfa,S.Pd.I</option>');
            employeeSelect.append('<option>Purno Budi AntoroS,Pd.I</option>');
            employeeSelect.append('<option>Rahmad Arif Setiawan</option>');
            employeeSelect.append('<option>Sahlan Rasyid,S.SPd,I,S.Psi.</option>');
            employeeSelect.append('<option>Shodiqin, S.Pd</option>');
            employeeSelect.append('<option>Susanti,S.E.</option>');
            employeeSelect.append('<option>Susmono</option>');
            employeeSelect.append('<option>Syamsiyati</option>');
            employeeSelect.append('<option>Triyadi, SPd.</option>');
            employeeSelect.append('<option>Muhammad Yusuf Fajri</option>');
        break;
        case 'PPTQ':
            employeeSelect.append('<option>Ust Ihsan</option>');
            employeeSelect.append('<option>Ust Fitri</option>');
            employeeSelect.append('<option>Ust Hasbina</option>');
            employeeSelect.append('<option>Ust Tursina</option>');
        break;
        case 'STIAA':
            employeeSelect.append('<option>Ayu lestari</option>');
            employeeSelect.append('<option>Rino Saputro</option>');
            employeeSelect.append('<option>Desy</option>');
            employeeSelect.append('<option>Syifa</option>');
            employeeSelect.append('<option>Latifah</option>');
            employeeSelect.append('<option>Tsabita</option>');
            employeeSelect.append('<option>Annisa</option>');
            employeeSelect.append('<option>Alisha</option>');
            employeeSelect.append('<option>Miftah</option>');
            employeeSelect.append('<option>Zaenab</option>');
            employeeSelect.append('<option>Azizah</option>');
            employeeSelect.append('<option>Aini</option>');
            employeeSelect.append('<option>Hikmah</option>');
            employeeSelect.append('<option>Tety</option>');
            employeeSelect.append('<option>Fatimah</option>');
            employeeSelect.append('<option>Farah</option>');
            employeeSelect.append('<option>Umni</option>');
            employeeSelect.append('<option>Naya</option>');
            employeeSelect.append('<option>Galang</option>');
            employeeSelect.append('<option>Hanif</option>');
            employeeSelect.append('<option>Syaiful</option>');
            employeeSelect.append('<option>Ahmad</option>');
        break;
        default:
        break;
    }
    }

    // Event listener for unit select change
    $('#unitSelect').change(function(){
    var selectedUnit = $(this).val();
    // Update employee options based on selected unit
    updateEmployeeOptions(selectedUnit);
    });

    // Initialize employee options based on default unit
    updateEmployeeOptions($('#unitSelect').val());
});

// Function to change input type to text
function changeInputType() {
    var employeeInput = $('#employeeSelect');
    employeeInput.replaceWith('<input type="text" class="form-control" id="employeeInput" placeholder="Masukkan nama lengkap karyawan" name="entry.1496297916">');
}